services:
  myapp:
    image: image-registry.openshift-image-registry.svc:5000/$NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
    labels:
      k8ify.expose: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$TEST_DOMAIN
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
