---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    k8ify.ref-slug: review-branch-1
    k8ify.service: myapp
  name: myapp-review-branch-1-env
stringData:
  admin_pw: passw0rd
